### ISSUE TITLE
About function

### ISSUE THREAD

**Issue by haha252** [Euphillya/SkyFolia#2]
Thank you very much for your code. I have successfully compiled it and placed it on the Folia1.20.2 server. However, I did not find a wiki on the usage and interface associated with it here (it seems that the wiki page has only one home?). Could you tell me how to use this plugin in the future?

Merci beaucoup pour votre code. Je l’ai compilé avec succès et l’ai placé sur le serveur Folia1.20.2. Cependant, je n’ai pas trouvé de wiki sur l’utilisation et l’interface associées ici (il semble que la page wiki n’ait qu’une seule page d’accueil ?). Pourriez-vous me dire comment utiliser ce plugin à l’avenir ?

(Translate by Newbing)

**Comment by Euphillya** [comment]
The plugin is not yet ready for real use, and there's still a lot to do. The wiki will be created as soon as the plugin is largely functional.

**Comment by haha252** [comment]
Thank you so much!
